Jaswanth feature (#19)
* Initial commit

Initial commit

* Complete prjt

Complete prjt

* 111

111

* updated props

updated props

* Added healthz resources

Added healthz resources

* changes

changes

* Update README.md

* Update maven.yml

* Update README.md

* Update README.md

* Update README.md

* Update maven.yml

---------

Co-authored-by: Jaswanth Marri <145034631+Jaswanth-marri@users.noreply.github.com>

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -36,6 +36,7 @@ name: Java CI with Maven
 
 on:
   pull_request:
+    types: ["opened"]
     branches: [ "main" ]
 
 jobs:
@@ -55,25 +56,28 @@ jobs:
       run: ls -R
     - name: Build with Maven
       run: mvn -B package --file ./webapp/pom.xml
+      
+    - name: Check if compilation was successful
+      run: mvn compile
 
-  merge:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Check out the code
-        uses: actions/checkout@v2
+  # merge:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - name: Check out the code
+  #       uses: actions/checkout@v2
 
-      - name: Merge pull request if build is successful
-        run: |
-          # Check if the build job was successful
-          if [ ${{ needs.build.result }} == 'success' ]; then
-            # Merge the pull request
-            git merge --no-ff ${{ github.event.pull_request.head.ref }}
-          else
-            # Print a message and exit with a non-zero code to fail the workflow
-            echo "Build failed, cannot merge the pull request."
-            exit 1
-          fi
+  #     - name: Merge pull request if build is successful
+  #       run: |
+  #         # Check if the build job was successful
+  #         if [ ${{ needs.build.result }} == 'success' ]; then
+  #           # Merge the pull request
+  #           git merge --no-ff ${{ github.event.pull_request.head.ref }}
+  #         else
+  #           # Print a message and exit with a non-zero code to fail the workflow
+  #           echo "Build failed, cannot merge the pull request."
+  #           exit 1
+  #         fi
 
 # Restrict merging to branch protection rules
 # Ensure 'main' branch is protected and require status checks to pass before merging
